name = "imagepicker"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "imagepicker"
bucket_name = "imagepicker"

[[d1_databases]]
binding = "DB"
database_name = "imagepicker-db"
database_id = "1176e663-7f85-498a-b16d-a22ec9aaeacc"

# 部署後在 Cloudflare Dashboard 設定 Secret：
# PHOTOGRAPHER_TOKEN = "你的秘密 token"
# 指令：wrangler secret put PHOTOGRAPHER_TOKEN
